<?xml version="1.0" encoding="utf-8"?><Database Name="QlyWebXemPhim" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-O232H9A\LOCAL;Initial Catalog=QlyWebXemPhim;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="QlyWebXemPhimConnectionString2" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Actor" Member="Actors">
    <Type Name="Actor">
      <Column Name="ActorID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ActorName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NamSinh" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Actor_Movie_Actor" Member="Movie_Actors" ThisKey="ActorID" OtherKey="ActorID" Type="Movie_Actor" />
    </Type>
  </Table>
  <Table Name="dbo.Admin" Member="Admins">
    <Type Name="Admin">
      <Column Name="AdminID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AdminName" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Hoten" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Country" Member="Countries">
    <Type Name="Country">
      <Column Name="CountryID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CountryName" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Association Name="Country_Movie" Member="Movies" ThisKey="CountryID" OtherKey="CountryID" Type="Movie" />
    </Type>
  </Table>
  <Table Name="dbo.Genre" Member="Genres">
    <Type Name="Genre">
      <Column Name="GenreID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GenreName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Genre_Movie_Genre" Member="Movie_Genres" ThisKey="GenreID" OtherKey="GenreID" Type="Movie_Genre" />
    </Type>
  </Table>
  <Table Name="dbo.Movie" Member="Movies">
    <Type Name="Movie">
      <Column Name="MovieID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MovieName" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CountryID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MoviePicture" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="MovieImage" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="ReleaseDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Type" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Url" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Association Name="Movie_Movie_Actor" Member="Movie_Actors" ThisKey="MovieID" OtherKey="MovieID" Type="Movie_Actor" />
      <Association Name="Movie_Movie_Genre" Member="Movie_Genres" ThisKey="MovieID" OtherKey="MovieID" Type="Movie_Genre" />
      <Association Name="Movie_Rating" Member="Ratings" ThisKey="MovieID" OtherKey="MovieID" Type="Rating" />
      <Association Name="Country_Movie" Member="Country" ThisKey="CountryID" OtherKey="CountryID" Type="Country" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Movie_Actor" Member="Movie_Actors">
    <Type Name="Movie_Actor">
      <Column Name="MovieID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ActorID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Actor_Movie_Actor" Member="Actor" ThisKey="ActorID" OtherKey="ActorID" Type="Actor" IsForeignKey="true" />
      <Association Name="Movie_Movie_Actor" Member="Movie" ThisKey="MovieID" OtherKey="MovieID" Type="Movie" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Movie_Genre" Member="Movie_Genres">
    <Type Name="Movie_Genre">
      <Column Name="MovieID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GenreID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Genre_Movie_Genre" Member="Genre" ThisKey="GenreID" OtherKey="GenreID" Type="Genre" IsForeignKey="true" />
      <Association Name="Movie_Movie_Genre" Member="Movie" ThisKey="MovieID" OtherKey="MovieID" Type="Movie" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Rating" Member="Ratings">
    <Type Name="Rating">
      <Column Name="RateID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CommentTxt" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DateSumitted" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ParentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MovieID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Movie_Rating" Member="Movie" ThisKey="MovieID" OtherKey="MovieID" Type="Movie" IsForeignKey="true" />
      <Association Name="User_Rating" Member="User" ThisKey="UserID" OtherKey="UserID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Association Name="User_Rating" Member="Ratings" ThisKey="UserID" OtherKey="UserID" Type="Rating" />
    </Type>
  </Table>
</Database>